# Generated by Django 3.1.5 on 2021-01-06 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttvdash', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ttvproject',
        ),
    ]
