# Generated by Django 3.1.4 on 2021-01-12 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttvdash', '0005_messageoftheday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='gredjawatan',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='jawatan',
            new_name='position',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='supervision',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
